### ISSUE TITLE
Run only on certain branch

### ISSUE THREAD

**Issue by perry-mitchell** [semantic-release/changelog#156]
Is there functionality that would allow me to specify which branch(es) to run the changelog generation on? I for instance want to avoid all pre-release versions from entering the changelog.. It's important for users to read the primary distribution release notes, but to not see the pre-release items as it just makes the log too busy and long-winded.

If not, would you consider a PR for such functionality?

**Comment by newbish** [comment]
was looking for the same thing so wrote this https://github.com/semantic-release/changelog/pull/157

**Comment by kingphil** [comment]
I could use this feature. How would you feel about the option being "branches: [...]" (as opposed to ignoreBranches)? This would have symmetry with the top-level "branches" array in .releaserc. I imagine the repos that would use this would have a list in mind where they do want the changelog modified, and a longer list of branches where they don't.

```
diff --git a/.releaserc.json b/.releaserc.json
index 094a34a..f5eb394 100644
--- a/.releaserc.json
+++ b/.releaserc.json
@@ -6,6 +6,7 @@
       "@semantic-release/changelog",
       {
         "changelogFile": "CHANGELOG.md",
+        "branches": ["master"]
       }
     ],
```

**Comment by hanseltime** [comment]
I see that the PR is still open. Looks like it has some extraneous files, etc.  I am currently going to augment this plugin for my own development purposes, but would like to ask if this is conceptually still a good feature.  I say yes, but with a larger use case:

We have a set of rapidly developed monorepos that are moving through any number of hot-fixes (into main), alpha releases (into develop), and release candidate fixes during UAT.  We also want to streamline a merge back process from main/release into develop.  However, the changelogs always conflict.  More that that, the changelogs contain lots of duplicate entries due to the alpha branch reporting the same notes as the released main branch (think git-flow merge parttern).

What I would like to do is actually write a CHANGELOG.md, CHANGELOG_DEVELOP.md, and CHANGELOG_RELEASE.md logs.  It would keep the overall change logs cleaner and reduce the complexity of the merge conflicts that I currently get due to some new alpha release conflicting with a hot-fix release.  Granted I will still have to merge resolve the difference in package versions but that can actually be resolved by setting a "theirs" rule for the incoming main branch since we actually want the alpha branches to now run against the newest version.

**Comment by newbish** [comment]
That doesn't sound like it would be too difficult and could be enough justification to make it something they could consider merging.

**Comment by travi** [comment]
semantic-release is not a general workflow tool. continuous integration and continuous deoloyment/release are enabled more easily with semantic-release through trunk-based development or github-flow. gitflow is not official supported, but is possible to simulate through misuse of pre-releases as is being described above. 

varying release behavior between branches in order to support release flows that are not intended for end-consumers adds significant complexity to the semantic-release project that would need to be supported long into the future of the project. since we have not heard requests for such features outside the desire to simulate gitflow-like workflows, this is not functionality that we are planning to accept at this time.

**Comment by hanseltime** [comment]
Good to know that it's not in scope for this plugin.  As for the comment about trunk-based flow, I think I'm a little unclear on how semantic-release is expecting github flow when they suggest multiple branch release channels.  

If we're just targeting separate major version branches this makes sense, but from the documentation, prerelease is discussed rather thoroughly as a separate channel and branch.  In that paradigm, git-flow would make sense.  I don't need this opened back up, but mainly wanted to leave this here for clarification for anyone who thinks the system is only for trunk-based git from the above comment.

**Comment by travi** [comment]
@hanseltime perhaps the additional explanation in https://github.com/semantic-release/changelog/pull/157#issuecomment-1135431728 can help. as i mentioned above, we recognize that the pre-release workflow can be used to simulate gitflow, but that is not the intended use of that type of workflow within semantic-release. projects can choose to use semantic-release in unsupported ways, but that choice may come with downsides, like this changelog behavior.

**Comment by newbish** [comment]
In other words, if you want this feature it needs to be implemented and maintained it as a plug-in not directly affiliated with semantic -release.
