### ISSUE TITLE
Version titles should be ##, not # (or at least configurable)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [semantic-release/changelog#279]
For accessibility, headings should increase level by 1. See https://github.com/DavidAnson/markdownlint/blob/2b2dc27f24a16a2afdf66d850a247f7ce02df6c8/doc/Rules.md#md001---heading-levels-should-only-increment-by-one-level-at-a-time & https://www.w3.org/WAI/tutorials/page-structure/headings.

However, this is the format generated by default today:

```md
# [1.4.0](https://github.com/org/package/compare/v1.3.0...v1.4.0) (2022-12-13)

### Features

- example feature ([#2](https://github.com/org/package/issues/1)) ([abc123](https://github.com/org/package/commit/abc123defghi4567))
```

Proposal: let's switch to...

```diff
- # [1.4.0]...
+ ## [1.4.0]...
```

**Comment by kleinfreund** [comment]
I agree. The document outline of the changelog is always incorrect this way because heading level 1 skips heading level 2 directly to heading level 3.

It would also be nice if `# Changelog` could be added to the start of the document if not present.

The changelog could be generated like this:

1. If no `h1` exists at line 1, column 1, add `# Changelog`<br>
   followed by an empty line<br>
   at position line 1, column 1.
2. Add an `h2` with the new version<br>
   followed by an empty line<br>
   at position line 3, column 1.
3. Add an `h3` with the change type<br>
   followed by an empty line<br>
   followed by the change type content<br>
   followed by an empty line<br>
   at position line 5, column 1.

```
# Changelog

## [1.4.0](#...)

### Features

...

## [1.3.2](#...)

### Bug Fixes

...
```

**Comment by travi** [comment]
is this still actually an issue? as mentioned in https://github.com/semantic-release/semantic-release/discussions/2312#discussioncomment-1865222, the release notes are generated by conventional-changelog. the issue that i linked to in that comment was resolved by setting all versions to always use an h2, which is the output that i see from recent releases generated by modern semantic-release

**Comment by JoshuaKGoldberg** [comment]
> recent releases generated by modern semantic-release

Could you post a reference for that? I've stopped using semantic-release myself and so haven't taken a look in a while. 😅

**Comment by travi** [comment]
> Could you post a reference for that?

github release notes, like https://github.com/semantic-release/changelog/releases/tag/v6.0.3, are generated the same way as changelog content

**Comment by JoshuaKGoldberg** [comment]
Nice, looks like this was fixed - thanks!

**Comment by kleinfreund** [comment]
For reference, if you're still seeing h1s for version headings, there's a chance you're using (directly or indirectly) the [conventional-changelog angular preset](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular). For this preset, the changelog generation will still produce h1s for versions (see issue: https://github.com/conventional-changelog/conventional-changelog/issues/942, see `header.hbs` template: [conventional-changelog-angular/templates/header.hbs](https://github.com/conventional-changelog/conventional-changelog/blob/73dd829fd1987ee30b60b6498c5c7b4069b72e17/packages/conventional-changelog-angular/templates/header.hbs)).
