### ISSUE TITLE
suppress changelog's for prereleases?

### ISSUE THREAD

**Issue by bryanlarsen** [semantic-release/changelog#51]
I'm using semantic-release 16.0.0-beta.19 which supports prereleases.

It would be really nice if this plugin could be configured to only update the changelog for full releases, skipping prereleases.

**Comment by pvdlg** [comment]
What would be the point of that? What's the problem with having a changelog entry for a pre-release?

**Comment by pvdlg** [comment]
Closing as no answer was provided

**Comment by mikecbrant** [comment]
+1 on need to address this issue (probably before prerelease functionality is out of beta).

Since adopting use of prerelease, we are finding that default behavior of this module is problematic as you begin to get prerelease notes intermigled with (duplicate) release notes once the changes are release into master release branch.

This causes us to have to manually correct changelog files after the master release :(

I guess alternately, rather than just having an option to potentially turn of this plugin for prerelease,  the release-notes-generator could be made to modify prerelease changelog entries into master release entries rather than just simply appending the duplicate master release notes into the changelog.  My guess is that this would be more complex to implement though.

**Comment by pvdlg** [comment]
If a feature is released as part of a beta, and then later released as part of a normal it will appear twice in the changelog. Once under the beta and once under the normal release.

How is that a problem?

That's an accurate depiction of what happened...And as a user reading the changelog, I would read only the content of the version I'm using. So if I'm on a beta version I would read the beta release changelog, and I would skip those if I'm on a regular version.

**Comment by bryanlarsen** [comment]
For us, it appears about 5 times in the changelog.  First in the feature prerelease branch, then in the story prerelease branch, then in the integration prerelease branch, then in the rc prerelease branch and then it finally hits master.   It seems excessive, but semantic-release is a big part of the automation making this process almost transparent to developers.

**Comment by pvdlg** [comment]
Why do you have so many pre-release branches?
Do you really need to publish a release at each of those steps?
The objective of a pre-release is to publish a version that will be used by a subset of users. Do you really have users using all those different version?
If not then don't release those. From the list you provided it seems only `rc` might actually be used by users. If it's the case release only from `rc` and not from integration and story.

**Comment by bryanlarsen** [comment]
Every single one of those prereleases is live on the interwebs, and semantic-release is a key part of making that easy.   This makes it extremely convenient for reviewers.

And every prerelease is published and used by a developer.  If module X is used by service S, they're often developed in parallel, so service S needs a lot of intermediate versions of module X at every stage.

**Comment by DiegoRBaquero** [comment]
Need this too

**Comment by yinzara** [comment]
+1 Absolutely needs to be a feature.  

My workflow is nearly identical to this. A feature starts in a feature branch (initial prerelease with first instance of changelog) which is published and distributed in special environments designed to test new feature, gets merged to develop when complete (duplicated in the "next" prerelease) and deployed to a shared environment, merged to release to verify before production (duplicated in "release candidates") and then merged to master when released  (duplicated again).

There should be a way to use the prior release version to determine the last entry in the log that corresponds to it and removes all those changelog entries before appending the generated changelog since that release.

**Comment by zanona** [comment]
I believe that one use case would be nightly builds: having the changelog updated every day, may indeed become a problem if it goes to nightly > alpha > beta > rc > stable, as it would create so many duplications that it could make the changelog difficult to read?

I often version each one of these releases to they can be identified, rolled back to, if needed. So this is where I'd use the version generated by the semantic-release in order to release those builds with unique version numbers, which is really helpful.

Sorry, hopefully I'm not missing something obvious here, but requesting that the changelog plugin ignores specific branches seems a sensible request to me?

Perhaps bumping the version number for each pre-release may not be a good idea at all, in which case It would be interesting to learn about a possible workaround to uniquely identify each one of those builds?

I hope this can be reconsidered. :)

**Comment by bradennapier** [comment]
I think it makes sense to have a setting to only generate the changelog on certain branches whereas the release notes would indicate every release and the notes for that release.

That way the `CHANGELOG.md` is a pure representation of the changes to the main release whereas the release notes would be the release-by-release view

**Comment by Miziak** [comment]
For in my team I introduced following solution:

Rename `.releaserc` to `release.config.js` and create your config around this snippet:
```javascript
const branch = process.env.CI_COMMIT_BRANCH

const config = {
  branches: ['master', { name: 'dev', prerelease: true }],
  plugins: ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator'],
}

if (config.branches.some(it => it === branch || (it.name === branch && !it.prerelease))) {
  config.plugins.push('@semantic-release/changelog', [
    '@semantic-release/git',
    {
      assets: ['CHANGELOG.md'],
      message: 'chore(release): ${nextRelease.version} \n\n${nextRelease.notes}',
    },
  ])
}

module.exports = config
```

`CI_COMMIT_BRANCH` env variable is populated with branch name by our CI provider which is GitLab, if you using something else feel free to grab this from another source
I hope it help someone ;)

**Comment by 1nVitr0** [comment]
I think this is definitely relevant. Prerelease branches often receieve updates frequently and in smaller increments than release branches. As prereleases are often for major releases all those little changes are written under giant capital headings for each prerelease.

This can make reading the changelog extremely cumbersome, especially if all the changes are then duplicated in the actual release. It would also be enough to provide a separate changelog file for prereleases, as they are only interesting for a select group of users.

**Comment by albert-a** [comment]
I just remove all prerelease entries from the changelog on release branch with sed:
```
    ["@semantic-release/exec", {
        "prepareCmd": "test ${branch.type} != release || sed -i '/^## \\[/h;x;/^[^]]*-/{x;d};x' CHANGELOG.md"
    }],
```
So for users there are no unnecessary prerelease entries. For beta testers they are. Everyone is happy.

**Comment by mtrezza** [comment]
In case it helps anyone, we are solving this by splitting the change logs per release type, see:

https://github.com/parse-community/parse-server/blob/b458dcec9122a523fa397db1fa06996aea3bdecb/release.config.js#LL26-L32

**Comment by esatterwhite** [comment]
@mtrezza 
> This should already be possible by creating a custom handlebar template and suppressing the output in the change log writer if the release is a pre-release

I could be wrong, but I don't think the change log has access to the release type. I think its just an array of commits, no? there is no `prerelease` or `isPrelease` property available in the templates

**Comment by marvinroman** [comment]
Here is an updated solution that combines some of the previous recommendations. I haven’t tested it on GitHub since I don’t use it often, but it should work.

```js
// Define the branches where releases should occur
const branches = [
    "production", // Main production release branch
    {"name": "*beta", "prerelease": true}, // Pre-release branches matching "beta"
    {"name": "*next", "prerelease": true} // Pre-release branches matching "next"
];

/**
 * Determines the CI platform and returns the corresponding semantic-release plugin configuration.
 *
 * @returns {string[]} An array containing the appropriate plugin for the CI platform:
 *                     - `["@semantic-release/github"]` for GitHub Actions
 *                     - `["@semantic-release/gitlab"]` for GitLab CI
 *                     - An empty array `[]` for unknown or local CI environments
 */
const getCIPlatformConfiguration = () => {
    if (process.env.GITHUB_ACTIONS) {
        // If the CI environment is GitHub Actions, return the GitHub plugin configuration
        return ["@semantic-release/github"];
    } else if (process.env.GITLAB_CI) {
        // If the CI environment is GitLab CI, return the GitLab plugin configuration
        return ["@semantic-release/gitlab"];
    } else {
        // Return an empty array for unknown CI platforms or local runs
        return [];
    }
};

/**
 * Checks if the current branch is a production release branch.
 * @returns {boolean} True if the branch is a production release branch, false otherwise.
 */
const isProductionBranch = () => {
    const branchName = process.env.CI_COMMIT_REF_NAME || process.env.GITHUB_REF_NAME;
    return branches.some((b) =>
        (typeof b === "string" && b === branchName) || // Direct match for production branch
        (b.name === branchName && !b.prerelease) // Ensure it's not a prerelease branch
    );
};

// Plugins for production releases
const releasePluginsForProduction = [
    "@semantic-release/changelog", // Generates and updates CHANGELOG.md
    "@semantic-release/npm", // Publishes the package to npm (optional)
    [
        "@semantic-release/git",
        {
            assets: [
                "CHANGELOG.md",
                ...[] // Add other files to commit during release
            ], 
            message: "chore(release): bumping version to $${nextRelease.version} [skip ci]" // Commit message format
        }
    ] // Commits the changelog and package files
];

// Plugin to replace the version field in the manifest file with the new release version
const replaceVersionInManifestPlugin = [
    "semantic-release-replace-plugin"
    // ... Add configuration to update version in manifest
];

module.exports = {
    branches,
    plugins: [
        "@semantic-release/commit-analyzer", // Analyze commit messages to determine version bumps
        ...isProductionBranch() ? replaceVersionInManifestPlugin : [], // Include version replacement plugin only for production branches
        "@semantic-release/release-notes-generator", // Generate release notes from commit history
        ...isProductionBranch() ? releasePluginsForProduction : [], // Include release plugins only for production branches
        ...(getCIPlatformConfiguration()) // Use GitLab or GitHub plugin based on CI platform
    ]
};
```

### How the Configuration Works:

- **`isProductionBranch`**: Determines whether the current branch is a production branch:
  - Checks if the branch is the main production branch or any non-prerelease branches listed in `branches`.

- **`getCIPlatformConfiguration`**: Checks the environment to determine the CI platform:
  - Returns `["@semantic-release/github"]` for GitHub Actions.
  - Returns `["@semantic-release/gitlab"]` for GitLab CI.
  - Returns an empty array `[]` for unknown or local environments.

This configuration ensures that only production branches run the full release process (including changelog updates and version bumps), while prerelease branches like `beta` or `next` exclude certain plugins, such as the changelog. It also dynamically includes plugins in the correct order and provides support for both GitHub and GitLab CI environments.
